### ISSUE TITLE
Hot res failure

### ISSUE THREAD

**Issue by Rinn** [horrible-little-slime/phccs#26]
I got an unable to equip outfit error because there wasn't a [metal meteoroid](https://kol.coldfront.net/thekolwiki/index.php/Metal_meteoroid) drop to create a [meteorite guard](https://kol.coldfront.net/thekolwiki/index.php/Meteorite_guard).

**Comment by Rinn** [comment]
I'll mention that when i commented out the [meteorite guard](https://kol.coldfront.net/thekolwiki/index.php/Meteorite_guard) line in the outfit requirement and ran again the script finished no problem, so it probably just needs to make it optional.

**Comment by spaghetti-squash** [comment]
Resolved!
